### ISSUE TITLE
[v1.0.9] Cannot compile gem on intel ( > 4th gen) on gcc < 4.9.0

### ISSUE THREAD

**Issue by alx75** [RubyCrypto/x25519#27]
The problem comes from the fact the x25519 is supported by the cpu because I use an intel > 4th gen [1] so x25519_precomputed is going to be compiled with arch haswell since this https://github.com/RubyCrypto/x25519/pull/25 .

However on gcc < 4.9.0 my arch is detected as core-avx2 and do not work with "-march haswell" ( error: bad value (haswell) for -march= switch )

OS: _CentOS Linux release 7.9.2009_ 
GCC:  _gcc version 4.8.5 20150623 (Red Hat 4.8.5-44)_ (version shipped with the os)
[1] cpu: Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz

Obvious workaround is to update to gcc >= 4.9.0 :) or use x25519 v1.0.8 however that would be nice if this gem could support compiling on gcc < 4.9.0 for intel 4th gen and above.

**Comment by tarcieri** [comment]
I'm not sure how to support this other than introspecting the compiler's available `march` flags which sounds like a fraught endeavor
