### ISSUE TITLE
Support for non-x86 architectures (including ARM)

### ISSUE THREAD

**Issue by tarcieri** [RubyCrypto/x25519#4]
The gem is presently not packaged in such a way it will build on non-x86 architectures.

It shouldn't be too hard as it already packages the portable ref10 implementation, but some work will be required in e.g. extconf.rb

**Comment by armfazh** [comment]
I am preparing the implementation using native 64-bit instructions for pre-Haswell processors.
According to my experience, the performance will be affected in comparison to the Haswell implementation, but I predict a faster execution in comparison to ref10.

**Comment by dentarg** [comment]
@tarcieri mind doing a release with the latest improvements in this area?

**Comment by tarcieri** [comment]
Released as v1.0.10

**Comment by dentarg** [comment]
Thanks!

**Comment by tarcieri** [comment]
Fixed by #36
